config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }

  root 'home#index'

  resources :users,
            only: [:new, :create, :index, :update],
            path: :invitations,
            controller: :invitations,
            as: :invitation

  resources :polls, except: [:edit, :update, :destroy]
  resources :votes, only: [:update] do
    collection do
      get 'vote'
      get 'done'
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
  has_many :polls

  validates_presence_of :name

  accepts_nested_attributes_for :users

  def active_users
    users.actives
  end

  def activate_user(email, activate)
    users.where(email: email).first.try(:update, active: activate)
  end
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :company
  has_many :poll_members
  has_many :users, through: :poll_members
  has_many :votes

  validates_presence_of :company

  before_save :create_vote_invitations

  scope :average_of_company, lambda { |company|
    average = 0
    polls = where(company: company)
    votes = Vote.where(poll: polls).where.not(value: nil)
    average = votes.sum(:value) / votes.count(:value).to_f unless votes.empty?
    average
  }

  def self.create_and_send_email(user_ids, company_id)
    poll = Poll.new(user_ids: user_ids, company_id: company_id)
    if poll.save!
      poll.users.each_with_index do |u, i|
        PollMailer.poll_invite(u, poll.votes[i], poll.created_at).deliver_now
      end
    end

    poll
  end

  def send_results_if_finished
    return if remaining > 0
    users.each do |user|
      PollMailer.poll_result(user, average, comments, created_at).deliver_now
    end
  end

  def average
    average = 0
    average = votes.sum(:value) / votes.count(:value).to_f if votes.try(:count, :value) > 0
    average
  end

  def comments
    votes.where.not(comment: nil).map{ |vote| vote.comment }
  end

  def remaining
    remaining = users.count - votes.try(:count, :value)
  end

  def create_vote_invitations
    (0..users.size - 1).each do
      self.votes.new
    end
  end
end

app/models/poll_member.rb
class PollMember < ActiveRecord::Base
  belongs_to :poll
  belongs_to :user

  validates_presence_of :poll, :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company
  has_many :poll_members
  has_many :polls, through: :poll_members

  validates_presence_of :company

  accepts_nested_attributes_for :company

  scope :actives, -> { where(active: true) }
  scope :actives_of_company, -> (company){ where(company: company, active: true) }

  def active_for_authentication?
    super && active
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :poll

  validates_presence_of :token, :poll

  before_validation :generate_token

  def save_rating!(rating, comment)
    if value.nil?
      update(value: rating, comment: comment)
    else
      errors.add(:value, "You already have voted")
    end

    self
  end

  def generate_token
    while true && token.nil? do
      self.token = SecureRandom.base64(10)
      break unless Vote.find_by token: self.token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  respond_to :html

  protected

  def current_company
    current_user.company
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index; end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  def index
    @users = current_company.users
  end

  def new
    @user = User.new
  end

  def create
    @user = User.invite! email: permitted_params[:email], company_id: current_company.id
    respond_with @user, location: { action: :index }
  end

  def update
    @user = current_company.activate_user permitted_params[:email], permitted_params[:active]
    respond_with @user, location: { action: :index }
  end

  protected

  def permitted_params
    params.require(:user).permit(:email, :active)
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @polls = current_company.polls
  end

  def show
    @poll = current_company.polls.find(params[:id])
  end

  def new
    @poll = build_poll
  end

  def create
    @poll = Poll.create_and_send_email permitted_params[:user_ids], current_company.id
    respond_with @poll, location: { action: :index }
  end

  protected

  def permitted_params
    permitted = params.require(:poll).permit(user_ids: [])
    permitted[:user_ids] = current_company.users.pluck(:id) & permitted[:user_ids].map(&:to_i)
    permitted
  end

  def build_poll
    @poll = Poll.new users: current_company.active_users
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :vote_by_token, except: [:done, :not_found]

  def vote
    redirect_to action: :done unless @vote.try(:value).nil?
  end

  def update
    @vote.save_rating!(permitted_params[:value], permitted_params[:comment])
    @vote.poll.send_results_if_finished
    respond_with @vote, location: { action: :done }
  end

  def done; end

  protected

  def permitted_params
    params.require(:vote).permit(:token, :value, :comment)
  end

  def vote_by_token
    @vote = Vote.find_by token: permitted_params[:token]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def votes_controller?
    params[:controller] == VotesController.name.underscore.gsub('_controller', '')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper

  FULL_STAR = "<i class='fa fa-star fa-2x'></i>"
  HALF_STAR = "<i class='fa fa-star-half-o fa-2x'></i>"
  EMPTY_STAR = "<i class='fa fa-star-o fa-2x'></i>"

  END_STATUS = "<i class='fa fa-check-circle'></i>".html_safe
  RUNNING_STATUS = "<i class='fa fa-play-circle'></i>".html_safe

  def poll_average_stars(average)
    stars = ""

    full_stars = average.to_i
    half_star = average - average.to_i >= 0.5 ? 1 : 0
    empty_stars = 5 - half_star - full_stars

    (0..full_stars - 1).each { |i| stars += FULL_STAR }
    stars += HALF_STAR if half_star > 0
    (0..empty_stars - 1).each { stars += EMPTY_STAR }

    stars.html_safe
  end

  def poll_status(remaining)
    remaining > 0 ? RUNNING_STATUS : END_STATUS
  end

  def poll_user_box(email)
    gravatar_image_tag(email, file_type: :png, alt: email, :'class' => 'checkbox-gravatar-img') +
    "<div class='poll-user-email'><b>#{email.gsub(/@.*/, '')}</b></div>".html_safe
  end
end

app/helpers/votes_helper.rb
module VotesHelper

  def created_at(date)
    date.strftime("%a. %B, %d %Y")
  end
end

app/views/invitations/_form.html.erb
<%= simple_form_for @user, url: url_for(action: :create, controller: :invitations), method: :post, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :email %>
  <%= error_span(@user[:email]) %>

  <%= f.button :submit, 'Invite', :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                invitation_index_path, :class => 'btn btn-default' %>
<% end %>

app/views/invitations/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:invitation_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.invitation_sent_at.try(:strftime, '%w %B %Y') %></td>
      <td><%= user.last_sign_in_at.try(:strftime, '%w %B %Y') %></td>
      <td>
      <% if user != current_user %>
        <% if user.active then %>
          <%= link_to 'Revoke Access',
              invitation_path(user, user: { email: user.email, active: false } ),
              method: :put,
              :class => 'btn btn-danger' %>
        <% else %>
          <%= link_to 'Allow Access',
              invitation_path(user, user: { email: user.email, active: true } ),
              method: :put,
              :class => 'btn btn-warning' %>
        <% end %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
new_invitation_path,
:class => 'btn btn-primary' %>

app/views/invitations/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<div class="row">
  <div class="col-lg-4">
    <%= render :partial => 'form' %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Hapiness Dashboard', root_path, class: 'navbar-brand' %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Dashboard', root_path %></li>
        <li><%= link_to 'Polls', polls_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><b><%= current_user.email %></b></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-cog fa-1x"></i> Mais <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to raw("<i class='fa fa-envelope-o'></i> Invitations"), invitation_index_path %></li>
            <li class="divider"></li>
            <li><%= link_to raw("<i class='fa fa-sign-out'></i> Sign Out"), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HapinessDashboard" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <% if user_signed_in? && !votes_controller? %>
      <%= render 'layouts/navbar' %>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="col-lg-6 col-lg-offset-3">
            <%= bootstrap_flash %>
          </div>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/polls/_form.html.erb
<%= simple_nested_form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.label :users %>
  <%= f.association :users,
                    label: '',
                    collection: @poll.users.map { |u|
                      [
                        poll_user_box(u.email),
                        { class: 'checkbox-gravatar' },
                        u.id,
                      ]
                    },
                    label_methods: :first,
                    value_method: :last,
                    include_hidden: false,
                    item_wrapper_class: 'checkbox-wrapper',
                    as: :check_boxes %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn btn-default' %>
<% end %>

app/views/polls/edit.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/polls/index.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <div class="main-average">
    <h3><%= poll_average_stars(Poll.average_of_company current_user.company) %></h3>
    <p><b><%=  number_with_precision Poll.average_of_company(current_user.company), precision: 1 %></b></p>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:users) %></th>
      <th>Rating</th>
      <th>Status</th>
      <th>Pending</th>
    </tr>
  </thead>
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to created_at(poll.created_at.to_time), poll_path(poll) %></td>
        <td>
          <% poll.users.each do |user| %>
            <%= gravatar_image_tag(user.email, file_type: :png, alt: user.email, class: 'polls-gravatar-img') %>
          <% end %>
        </td>
        <td>
          <b><%= number_with_precision(poll.average.to_f, precision: 1) %>/<%= poll_average_stars poll.average %></b>
        </td>
        <td><%= poll_status poll.remaining %></td>
        <td><%= poll.remaining %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_poll_path,
            :class => 'btn btn-primary' %>

app/views/polls/new.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/polls/show.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="main-average">
  <h3><%= poll_average_stars @poll.average  %></h3>
  <p><b><%=  number_with_precision @poll.average.to_f, precision: 1 %></b></p>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:users) %></strong></dt>
  <dd>
    <% @poll.users.each do |user| %>
      <%= gravatar_image_tag(user.email, file_type: :png, alt: user.email, class: 'polls-gravatar-img') %>
    <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:comments) %></strong></dt>
  <dd>
    <% @poll.comments.each do |comment| %>
      <dt><strong>-</strong></dt>
      <dd><%= comment %></dd>
    <% end %>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn btn-default'  %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/votes/_form.html.erb
<%= simple_form_for @vote do |f| %>
  <%= f.input :value, collection: 1..5,
              wrapper_html: { id: 'rating-radio-group' },
              label: 'Rating',
              item_wrapper_class: 'radio-wrapper',
              as: :radio_buttons %>
  <%= error_span(@vote[:value]) %>

  <div id="rating-warning" class="alert alert-warning" style="display: none">
    <strong>Hey!</strong> Your opinion is important for us!
  </div>

  <%= f.input :comment %>
  <%= error_span(@vote[:comment]) %>

  <%= f.hidden_field :token %>

  <%= f.button :submit, 'Vote', :class => 'btn-primary' %>
<% end %>

app/views/votes/done.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="panel panel-primary devise-box">
      <div class="panel-heading">
        <div class="panel-title"><h2 class="devise-box-title"><b>Voted!</b></h2></div>
      </div>
      <div class="panel-body">
        <h3 class="vote-message">Vote computed :D</h3>
      </div>
    </div>
  </div>
</div>

app/views/votes/vote.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="panel panel-primary devise-box">
      <div class="panel-heading">
        <div class="panel-title"><h2 class="devise-box-title"><b>Secret Vote</b></h2></div>
      </div>
      <div class="panel-body">
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</div>